// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWfyTHG9LSSSUl2clOz7nvLnkGTUilW6k',
    appId: '1:1003268097101:web:220dcb7d7b353feeb4c804',
    messagingSenderId: '1003268097101',
    projectId: 'metan-chat',
    authDomain: 'metan-chat.firebaseapp.com',
    storageBucket: 'metan-chat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfoqA2NdN9AXVixNtqkk3Nz-DoHbYCxMk',
    appId: '1:1003268097101:android:5d3da6751b278c8ab4c804',
    messagingSenderId: '1003268097101',
    projectId: 'metan-chat',
    storageBucket: 'metan-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_UsdYwoAgvW5iRKydKNamz2KRXnteNHg',
    appId: '1:1003268097101:ios:5ece7a35f9f346ddb4c804',
    messagingSenderId: '1003268097101',
    projectId: 'metan-chat',
    storageBucket: 'metan-chat.firebasestorage.app',
    iosBundleId: 'com.example.gymApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_UsdYwoAgvW5iRKydKNamz2KRXnteNHg',
    appId: '1:1003268097101:ios:5ece7a35f9f346ddb4c804',
    messagingSenderId: '1003268097101',
    projectId: 'metan-chat',
    storageBucket: 'metan-chat.firebasestorage.app',
    iosBundleId: 'com.example.gymApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWfyTHG9LSSSUl2clOz7nvLnkGTUilW6k',
    appId: '1:1003268097101:web:906ce42f8797a48ab4c804',
    messagingSenderId: '1003268097101',
    projectId: 'metan-chat',
    authDomain: 'metan-chat.firebaseapp.com',
    storageBucket: 'metan-chat.firebasestorage.app',
  );
}
